version: '3'

services:
  besu:
    image: hyperledger/besu:24.3.0
    command:
      - "--network=goerli"
      - "--host-allowlist=*"
      - "--sync-mode=X_CHECKPOINT"
      - "--rpc-http-enabled"
      - "--rpc-http-cors-origins=*"
      - "--rpc-http-api=ETH,NET,CLIQUE,DEBUG,MINER,NET,PERM,ADMIN,EEA,TXPOOL,PRIV,WEB3"
      - "--engine-jwt-secret=/opt/besu/data/data/jwtsecret.hex"
      - "--engine-host-allowlist=*"
      - "--engine-rpc-enabled=true"
    container_name: besu-node
    ports:
      - "8545:8545"
      - "30303:30303"
      - "8551:8551"
    volumes:
      - ./volumes/besu:/opt/besu/data
